2025-08-24 08:47:41,226 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 08:47:41,493 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 08:53:09,463 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 08:53:09,726 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 08:53:29,709 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 08:53:29,709 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 08:53:35,748 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 08:53:35,748 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 10:23:21,461 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 10:23:21,461 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 10:24:07,958 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 10:24:07,958 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 10:24:14,037 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 10:24:14,037 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
2025-08-24 10:24:23,252 - causalllm.llm_client.openai - INFO - __init__:18 - Initializing OpenAI client
2025-08-24 10:24:23,252 - causalllm.llm_client.openai - ERROR - __init__:31 - Invalid OpenAI credentials - using default placeholders
